resources:
  apps:
    autostrategist-ai:
      name: 'autostrategist-ai'
      source_code_path: '../app/'

      resources:
        - name: 'artifactory'
          description: 'Artifactory volume for AutoStrategist-AI'
          uc_securable:
            permission: 'READ_VOLUME'
            securable_type: 'VOLUME'
            securable_full_name: 'workspace.car_sales.artifactory'
        # - name: 'llm'
        #   description: 'LLM volume for AutoStrategist-AI'
        #   serving_endpoint:
        #     name: 'llm-serving-endpoint'
        #     permission: 'CAN_QUERY'
