command: [
  "streamlit", 
  "run",
  "app.py"
]

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: MLFLOW_TRACKING_URI
    value: "databricks"
  - name: MLFLOW_REGISTRY_URI
    value: "databricks-uc"
  - name: WHEELS_MODULE
    value: "true"
  - name: DATABRICKS_SERVERLESS_COMPUTE_ID
    value: "auto"
  - name: UC_MODEL_PATH
    value: workspace.car_sales.car_sales_workflow_model
  - name: MODEL_ALIAS
    value: champion